apiVersion: v1
entries:
  helmchecker:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-02T08:05:35.234665Z"
    description: A Kubernetes CronJob that checks for outdated Helm charts and creates
      pull requests for updates
    digest: 6d8f9debdd23772774c5983dcd59c729a7ee407df74a5b67f3f26b498973446d
    home: https://github.com/marccoxall/helmchecker
    keywords:
    - helm
    - charts
    - kubernetes
    - automation
    - updates
    maintainers:
    - email: marc@example.com
      name: Marc Coxall
    name: helmchecker
    sources:
    - https://github.com/marccoxall/helmchecker
    type: application
    urls:
    - https://ninjatec.github.io/helmchecker/helmchecker-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-02T08:05:35.233525Z"
